const GET_COUNTRIES = 'GET_COUNTRIES';
const COUNTRY = 'COUNTRY';
const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
const ADD_ACTIVITY = 'ADD_ACTIVITY';

module.exports = {
    GET_COUNTRIES,
    COUNTRY,
    SEARCH_COUNTRY,
    ADD_ACTIVITY
}