const GET_COUNTRIES = 'GET_COUNTRIES';
const FILTER_COUNTRIES_BY_CONTINENT = 'FILTER_COUNTRIES';
const FILTER_COUNTRIES_ORD_NAME = 'FILTER_COUNTRIES_ORD_NAME';
const COUNTRY = 'COUNTRY';
const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
const ADD_ACTIVITY = 'ADD_ACTIVITY';

module.exports = {
    GET_COUNTRIES,
    FILTER_COUNTRIES_BY_CONTINENT,
    FILTER_COUNTRIES_ORD_NAME,
    COUNTRY,
    SEARCH_COUNTRY,
    ADD_ACTIVITY
}