const GET_COUNTRIES = 'GET_COUNTRIES';
const FILTER_COUNTRIES_BY_CONTINENT = 'FILTER_COUNTRIES';
const FILTER_COUNTRIES_ORD_NAME = 'FILTER_COUNTRIES_ORD_NAME';
const FILTER_COUNTRIES_ORD_POPULATION = 'FILTER_COUNTRIES_ORD_POPULATION';
const COUNTRY = 'COUNTRY';
const SEARCH_COUNTRY_BY_NAME = 'SEARCH_COUNTRY_BY_NAME';
const ADD_ACTIVITY = 'ADD_ACTIVITY';

module.exports = {
    GET_COUNTRIES,
    FILTER_COUNTRIES_BY_CONTINENT,
    FILTER_COUNTRIES_ORD_NAME,
    FILTER_COUNTRIES_ORD_POPULATION,
    SEARCH_COUNTRY_BY_NAME,
    COUNTRY,
    ADD_ACTIVITY
}